# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 32) do

  create_table "appearances", :force => true do |t|
    t.integer "game_id"
    t.integer "team_id"
    t.integer "player_id"
    t.integer "outs",        :default => 0, :null => false
    t.integer "runs",        :default => 0, :null => false
    t.integer "hits",        :default => 0, :null => false
    t.integer "walks",       :default => 0, :null => false
    t.integer "strike_outs", :default => 0, :null => false
    t.integer "home_runs",   :default => 0, :null => false
  end

  create_table "comments", :force => true do |t|
    t.integer  "player_id"
    t.integer  "sender_id"
    t.text     "body"
    t.datetime "created_at"
  end

  create_table "contracts", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "player_id"
    t.integer  "team_id"
    t.boolean  "accepted"
  end

  create_table "divisions", :force => true do |t|
    t.integer "league_id"
    t.string  "name"
  end

  create_table "games", :force => true do |t|
    t.date    "date"
    t.integer "home_team_id"
    t.integer "away_team_id"
    t.integer "home_line_score_id"
    t.integer "away_line_score_id"
    t.integer "winning_pitcher_id"
    t.integer "losing_pitcher_id"
    t.integer "save_pitcher_id"
    t.integer "season_id"
    t.integer "winner_id"
    t.integer "loser_id"
  end

  create_table "league_topics", :force => true do |t|
  end

  create_table "leagues", :force => true do |t|
    t.string  "name"
    t.integer "commissioner_id"
  end

  add_index "leagues", ["commissioner_id"], :name => "index_leagues_on_commissioner_id"

  create_table "line_scores", :force => true do |t|
    t.integer "one",   :default => 0, :null => false
    t.integer "two",   :default => 0, :null => false
    t.integer "three", :default => 0, :null => false
    t.integer "four",  :default => 0, :null => false
    t.integer "five",  :default => 0, :null => false
  end

  create_table "messages", :force => true do |t|
    t.text     "body"
    t.integer  "player_id"
    t.integer  "topic_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "messages", ["player_id"], :name => "index_messages_on_player_id"
  add_index "messages", ["topic_id"], :name => "index_messages_on_topic_id"

  create_table "pictures", :force => true do |t|
    t.integer "parent_id"
    t.string  "content_type"
    t.string  "filename"
    t.string  "thumbnail"
    t.integer "size"
    t.integer "width"
    t.integer "height"
    t.string  "type"
  end

  create_table "players", :force => true do |t|
    t.string   "email"
    t.string   "password_hash",        :limit => 40
    t.string   "password_salt",        :limit => 40
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "first_name",                         :default => "",    :null => false
    t.string   "last_name",                          :default => "",    :null => false
    t.integer  "league_id"
    t.integer  "team_id"
    t.boolean  "prospective_owner",                  :default => false
    t.string   "bats"
    t.string   "throws"
    t.date     "birthday"
    t.string   "hometown"
    t.string   "pitches"
    t.text     "bio"
    t.string   "contact"
    t.string   "homepage"
    t.integer  "avatar_id"
    t.datetime "forum_checked_at"
    t.string   "password_reset_token"
    t.datetime "team_checked_at"
  end

  add_index "players", ["league_id"], :name => "index_players_on_league_id"
  add_index "players", ["team_id"], :name => "index_players_on_team_id"

  create_table "seasons", :force => true do |t|
    t.integer "league_id"
    t.string  "name"
    t.string  "url"
  end

  create_table "starts", :force => true do |t|
    t.integer "game_id"
    t.integer "player_id"
    t.integer "team_id"
    t.integer "at_bats",     :default => 0, :null => false
    t.integer "singles",     :default => 0, :null => false
    t.integer "doubles",     :default => 0, :null => false
    t.integer "triples",     :default => 0, :null => false
    t.integer "home_runs",   :default => 0, :null => false
    t.integer "walks",       :default => 0, :null => false
    t.integer "strike_outs", :default => 0, :null => false
    t.integer "rbis",        :default => 0, :null => false
  end

  create_table "teams", :force => true do |t|
    t.string  "name"
    t.integer "league_id"
    t.integer "owner_id"
    t.integer "logo_id"
    t.text    "bio"
    t.string  "abbreviation"
    t.integer "division_id"
  end

  add_index "teams", ["league_id"], :name => "index_teams_on_league_id"
  add_index "teams", ["owner_id"], :name => "index_teams_on_owner_id"

  create_table "topics", :force => true do |t|
    t.string   "title"
    t.integer  "player_id"
    t.datetime "created_at"
    t.string   "type"
    t.integer  "league_id"
    t.integer  "team_id"
    t.datetime "replied_at"
    t.integer  "replied_by"
  end

  add_index "topics", ["player_id"], :name => "index_topics_on_player_id"
  add_index "topics", ["league_id"], :name => "index_topics_on_league_id"
  add_index "topics", ["team_id"], :name => "index_topics_on_team_id"

end
